# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 689ef428782670ddb79e923cb488a281dd63e6621753a1637fe77e64627eb4d79f33e0c1c5caca62e8367178723d76180037a91e0cce916b4b1db9e1059ea172

test:
  secret_key_base: ad6a5acc69903a58f8acbd8ffc733f67d550eb493fe90e8174111dcedfdeec9d542a0483e532b85d9cb7f354e2fcb716bc1a4afa8efd63c4831c8393c6d60b71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
